/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medical_billing_system;

import javax.swing.JOptionPane;
import java.sql.*;

public class credential_change_form extends javax.swing.JFrame
{
    int x;
    
    public credential_change_form(int x)
    {
        initComponents();
        this.x=x;
        
         setDefaultCloseOperation(credential_change_form.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel3 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        lbl_ = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_update_credentials = new javax.swing.JLabel();
        lbl_new_password = new javax.swing.JLabel();
        txt_pet_name = new javax.swing.JTextField();
        lbl_new_username = new javax.swing.JLabel();
        pf_pwd2 = new javax.swing.JPasswordField();
        lbl_confirm_password = new javax.swing.JLabel();
        pf_pwd1 = new javax.swing.JPasswordField();
        btn_update = new javax.swing.JButton();
        lbl_new_username1 = new javax.swing.JLabel();
        txt_email_id = new javax.swing.JTextField();
        lbl_question = new javax.swing.JLabel();
        lbl_question1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPasswordField1.setText("jPasswordField1");

        lbl_.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_.setForeground(new java.awt.Color(102, 102, 102));
        lbl_.setText("Don't have an account? ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(243, 243, 243));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_update_credentials.setBackground(new java.awt.Color(26, 179, 148));
        lbl_update_credentials.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_update_credentials.setForeground(new java.awt.Color(26, 179, 148));
        lbl_update_credentials.setText("Update Credentials");

        lbl_new_password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_new_password.setText("New Password");

        txt_pet_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_pet_name.setForeground(new java.awt.Color(102, 102, 102));

        lbl_new_username.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_new_username.setText("Enter Your Pet Name");

        lbl_confirm_password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_confirm_password.setText("Confirm Password");

        btn_update.setBackground(new java.awt.Color(26, 179, 148));
        btn_update.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_updateActionPerformed(evt);
            }
        });

        lbl_new_username1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_new_username1.setText("Enter Email Address");

        txt_email_id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_email_id.setForeground(new java.awt.Color(102, 102, 102));

        lbl_question.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_question.setForeground(new java.awt.Color(102, 102, 102));
        lbl_question.setText("Don't have an Account?");

        lbl_question1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_question1.setForeground(new java.awt.Color(26, 179, 148));
        lbl_question1.setText("Sign Up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_question1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_question, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pf_pwd1)
                                .addComponent(pf_pwd2)
                                .addComponent(lbl_confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_pet_name, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                .addComponent(lbl_new_username, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_email_id, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                            .addComponent(lbl_new_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lbl_update_credentials)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_update_credentials, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_new_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_email_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_new_username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pet_name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_pwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_pwd2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_question)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_question1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_updateActionPerformed
    {//GEN-HEADEREND:event_btn_updateActionPerformed
        // TODO add your handling code here:
        
        if(txt_email_id.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please Enter Email ID");
            return;
        }
         if(txt_pet_name.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please Enter Pet Name");
            return;
        }
        if(pf_pwd1.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please Enter Password");
            return;
        }
         if(pf_pwd2.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please Confirm Password");
            return;
        }
         if(pf_pwd1.getText().equals(pf_pwd2.getText()))
         {
              
         }
         else
         {
             JOptionPane.showMessageDialog(this,"Password Not Matched\nEnter Password Again");
              return;
         }
         
         try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","Thoke@123");
            
            String query = "select * from `medical_store`.`signup` where email_id=?";
            
            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setString(1, txt_email_id.getText());
            
            ResultSet rs;
            rs = pst.executeQuery();
            
            if(rs.next())
            {
                 JOptionPane.showMessageDialog(this, "Record Found !!");
                 
                  if(txt_pet_name.getText().equals(rs.getString("pet_name")))
                  {
                        
                  }
                  else
                  {
                      JOptionPane.showMessageDialog(this,"Enter Correct Pet Name");
                      return;
                  }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "You don't have an Account\n Please Sign up to Continue");
                return;
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error !!\n Try Again");
        }           
         
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","Thoke@123");
            
            String query;
            query = "UPDATE `medical_store`.`signup` SET `email_id` = ?, `pwd` = ? WHERE (`email_id` = ?)";
            
            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setString(1,txt_email_id.getText());
            pst.setString(2,pf_pwd1.getText());
            pst.setString(3,txt_email_id.getText());
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Username and Password Updated Sucessfully !!");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Username and Password Updation Failed !!");
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(credential_change_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(credential_change_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(credential_change_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(credential_change_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                credential_change_form frame = new credential_change_form(0);
                 
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private java.awt.Label lbl_;
    private javax.swing.JLabel lbl_confirm_password;
    private javax.swing.JLabel lbl_new_password;
    private javax.swing.JLabel lbl_new_username;
    private javax.swing.JLabel lbl_new_username1;
    private javax.swing.JLabel lbl_question;
    private javax.swing.JLabel lbl_question1;
    private javax.swing.JLabel lbl_update_credentials;
    private javax.swing.JPasswordField pf_pwd1;
    private javax.swing.JPasswordField pf_pwd2;
    private javax.swing.JTextField txt_email_id;
    private javax.swing.JTextField txt_pet_name;
    // End of variables declaration//GEN-END:variables
}
