/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medical_billing_system;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class del_has_medicines extends javax.swing.JFrame
{
    int id;
    
    public del_has_medicines(int x)
    {
        id=x;
        initComponents();
        
        date_expiry_date.setDateFormatString("yyyy-MM-dd");
        
         setDefaultCloseOperation(del_has_medicines.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_medicines = new javax.swing.JTable();
        btn_add_row = new javax.swing.JButton();
        lbl_quantity = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        lbl_selling_price = new javax.swing.JLabel();
        lbl_med_name = new javax.swing.JLabel();
        txt_cost_price = new javax.swing.JTextField();
        txt_purpose = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        lbl_cost_price = new javax.swing.JLabel();
        txt_selling_price = new javax.swing.JTextField();
        lbl_purpose = new javax.swing.JLabel();
        txt_med_name = new javax.swing.JTextField();
        lbl_expiry_date = new javax.swing.JLabel();
        date_expiry_date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));

        jPanel2.setBackground(new java.awt.Color(26, 179, 148));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("List of Medicines");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_submit.setBackground(new java.awt.Color(26, 179, 148));
        btn_submit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_submitActionPerformed(evt);
            }
        });

        tbl_medicines.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbl_medicines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String []
            {
                "Medicine Name", "Description", "Quantity", "Expiry Date", "Cost Price", "Selling Price"
            }
        ));
        tbl_medicines.setToolTipText("");
        tbl_medicines.setRowHeight(25);
        jScrollPane1.setViewportView(tbl_medicines);

        btn_add_row.setBackground(new java.awt.Color(26, 179, 148));
        btn_add_row.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_add_row.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_row.setText("Add Row");
        btn_add_row.setToolTipText("");
        btn_add_row.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_add_rowActionPerformed(evt);
            }
        });

        lbl_quantity.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_quantity.setText("Enter Quantity");

        txt_quantity.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lbl_selling_price.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_selling_price.setText("Enter Selling Price");

        lbl_med_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_med_name.setText("Enter Medicine Name");

        txt_cost_price.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_purpose.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btn_delete.setBackground(new java.awt.Color(26, 179, 148));
        btn_delete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.setToolTipText("");
        btn_delete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_deleteActionPerformed(evt);
            }
        });

        lbl_cost_price.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_cost_price.setText("Enter Cost Price");

        txt_selling_price.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lbl_purpose.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_purpose.setText("Enter Purpose");

        txt_med_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lbl_expiry_date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_expiry_date.setText("Enter Expiry Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl_med_name, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_med_name, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                        .addComponent(lbl_expiry_date, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(date_expiry_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_purpose, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_purpose, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_cost_price, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_cost_price, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(57, 57, 57)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_selling_price, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_selling_price, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_submit, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_add_row, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(69, 69, 69)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_med_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_purpose, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_purpose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_med_name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_selling_price, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cost_price, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_expiry_date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_cost_price, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_selling_price, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date_expiry_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add_row, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_submitActionPerformed
    {//GEN-HEADEREND:event_btn_submitActionPerformed
        // TODO add your handling code here:

        try
        {
            // Establish the connection
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","Thoke@123");

            // Prepare the SQL INSERT statement
            String sql = "INSERT INTO medical_store.delivery_has_medicines (del_id, med_name, purpose,quantity,expiry_date,cost_price,selling_price) VALUES (?, ?, ?,?,?,?,?)";
            PreparedStatement pst= con.prepareStatement(sql);

            // Get the TableModel from JTable
            DefaultTableModel model = (DefaultTableModel) tbl_medicines.getModel();

            // Loop through each row in the JTable
            for (int i = 0; i < model.getRowCount(); i++)
            {
                // Set the values for each column
                pst.setInt(1, id);
                pst.setObject(2, model.getValueAt(i, 0));
                pst.setObject(3, model.getValueAt(i, 1));
                pst.setObject(4, model.getValueAt(i, 2));
                pst.setObject(5, model.getValueAt(i, 3));
                pst.setObject(6, model.getValueAt(i, 4));
                pst.setObject(7, model.getValueAt(i, 5));

                // Execute the INSERT statement
                pst.executeUpdate();
            }

            JOptionPane.showMessageDialog(this,"Medicines Inserted Sucessfully!!");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"Medicines Not Inserted!! "+e);
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_add_rowActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_add_rowActionPerformed
    {//GEN-HEADEREND:event_btn_add_rowActionPerformed
        // TODO add your handling code here:

        if(txt_purpose.getText().equals("") || txt_quantity.getText().equals("") || txt_cost_price.getText().equals("") || txt_purpose.getText().equals("") || txt_selling_price.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter All Data!!");
        }
        else
        {
            java.util.Date utilDate = date_expiry_date.getDate();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            
            Object[] data = {txt_med_name.getText(),txt_purpose.getText(),txt_quantity.getText(),sqlDate,txt_cost_price.getText(),txt_selling_price.getText()};

            DefaultTableModel model = (DefaultTableModel) tbl_medicines.getModel();

            model.addRow(data);

            JOptionPane.showMessageDialog(this, "Data Added Successfully!!");

            txt_med_name.setText("");
            txt_purpose.setText("");
            txt_quantity.setText("");
            txt_cost_price.setText("");
            txt_selling_price.setText("");
        }
    }//GEN-LAST:event_btn_add_rowActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_deleteActionPerformed
    {//GEN-HEADEREND:event_btn_deleteActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) tbl_medicines.getModel();

        if(tbl_medicines.getSelectedRowCount()==1)
        {
            model.removeRow(tbl_medicines.getSelectedRow());
        }
        else
        {
            if(tbl_medicines.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"Table is Empty!!");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Please Select Single Row for Delete!!");
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(del_has_medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(del_has_medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(del_has_medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(del_has_medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                del_has_medicines frame = new del_has_medicines(0);
                 
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_row;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_submit;
    private com.toedter.calendar.JDateChooser date_expiry_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cost_price;
    private javax.swing.JLabel lbl_expiry_date;
    private javax.swing.JLabel lbl_med_name;
    private javax.swing.JLabel lbl_purpose;
    private javax.swing.JLabel lbl_quantity;
    private javax.swing.JLabel lbl_selling_price;
    private javax.swing.JTable tbl_medicines;
    private javax.swing.JTextField txt_cost_price;
    private javax.swing.JTextField txt_med_name;
    private javax.swing.JTextField txt_purpose;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_selling_price;
    // End of variables declaration//GEN-END:variables
}
