/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medical_billing_system;

import java.sql.*;

import java.awt.CheckboxGroup;
import javax.swing.JOptionPane;

public class Employee_form extends javax.swing.JFrame
{
    public Employee_form()
    {
        initComponents();
  
        date_bdate.setDateFormatString ("yyyy-MM-dd");
        date_jdate.setDateFormatString ("yyyy-MM-dd");
        
         setDefaultCloseOperation(Employee_form.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        textField7 = new java.awt.TextField();
        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        label1 = new java.awt.Label();
        panel3 = new java.awt.Panel();
        label2 = new java.awt.Label();
        txt_lname = new java.awt.TextField();
        label3 = new java.awt.Label();
        txt_fname = new java.awt.TextField();
        label4 = new java.awt.Label();
        txt_mname = new java.awt.TextField();
        label5 = new java.awt.Label();
        txt_contact_no = new java.awt.TextField();
        label7 = new java.awt.Label();
        txt_adhar_no = new java.awt.TextField();
        label8 = new java.awt.Label();
        label10 = new java.awt.Label();
        txt_role = new java.awt.TextField();
        label11 = new java.awt.Label();
        txt_email_id = new java.awt.TextField();
        label9 = new java.awt.Label();
        txt_area_address = new java.awt.TextArea();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label6 = new java.awt.Label();
        label14 = new java.awt.Label();
        txt_account_no = new java.awt.TextField();
        btn_submit = new java.awt.Button();
        date_bdate = new com.toedter.calendar.JDateChooser();
        date_jdate = new com.toedter.calendar.JDateChooser();
        cmb_gender = new javax.swing.JComboBox<>();
        lbl_photo = new java.awt.Label();
        txt_salary = new java.awt.TextField();
        btn_upload = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();

        textField7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textField7.setForeground(new java.awt.Color(102, 102, 102));
        textField7.setText("textField1");
        textField7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textField7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(243, 243, 243));

        panel2.setBackground(new java.awt.Color(26, 179, 148));
        panel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        panel2.setForeground(new java.awt.Color(255, 255, 255));

        label1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Employee Information");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel3.setBackground(new java.awt.Color(243, 243, 243));
        panel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        label2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label2.setText("Enter Middle Name ");

        txt_lname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_lname.setForeground(new java.awt.Color(102, 102, 102));
        txt_lname.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_lnameActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label3.setText("Enter First Name ");

        txt_fname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_fname.setForeground(new java.awt.Color(102, 102, 102));
        txt_fname.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_fnameActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label4.setText("Enter Last Name ");

        txt_mname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_mname.setForeground(new java.awt.Color(102, 102, 102));
        txt_mname.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_mnameActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label5.setText("Enter DOB");

        txt_contact_no.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_contact_no.setForeground(new java.awt.Color(102, 102, 102));
        txt_contact_no.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_contact_noActionPerformed(evt);
            }
        });

        label7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label7.setText("Enter Adhar No");

        txt_adhar_no.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_adhar_no.setForeground(new java.awt.Color(102, 102, 102));
        txt_adhar_no.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_adhar_noActionPerformed(evt);
            }
        });

        label8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label8.setText("Select Gender");

        label10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label10.setText("Enter Role");

        txt_role.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_role.setForeground(new java.awt.Color(102, 102, 102));
        txt_role.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_roleActionPerformed(evt);
            }
        });

        label11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label11.setText("Enter Email ID");

        txt_email_id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_email_id.setForeground(new java.awt.Color(102, 102, 102));
        txt_email_id.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_email_idActionPerformed(evt);
            }
        });

        label9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label9.setText("Enter Address");

        label12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label12.setText("Enter Contact No");

        label13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label13.setText("Enter Joining Date");

        label6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label6.setText("Enter Salary");

        label14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label14.setText("Enter Account No");

        txt_account_no.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_account_no.setForeground(new java.awt.Color(102, 102, 102));
        txt_account_no.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_account_noActionPerformed(evt);
            }
        });

        btn_submit.setBackground(new java.awt.Color(26, 179, 148));
        btn_submit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setLabel("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_submitActionPerformed(evt);
            }
        });

        date_bdate.setDateFormatString("yyyy-MM-dd");

        cmb_gender.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        lbl_photo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_photo.setText("Upload Photo");

        txt_salary.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_salary.setForeground(new java.awt.Color(102, 102, 102));
        txt_salary.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_salaryActionPerformed(evt);
            }
        });

        btn_upload.setBackground(new java.awt.Color(26, 179, 148));
        btn_upload.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_upload.setForeground(new java.awt.Color(255, 255, 255));
        btn_upload.setText("Click Photo");
        btn_upload.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_uploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_role, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email_id, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_jdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_contact_no, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_account_no, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(date_bdate, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmb_gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(609, 609, 609)))
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_area_address, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_adhar_no, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_photo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_salary, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(btn_upload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_contact_no, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txt_role, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(cmb_gender))
                .addGap(34, 34, 34)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_email_id, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txt_adhar_no, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(date_bdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_account_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date_jdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txt_salary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_photo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_area_address, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollBar1.setBackground(new java.awt.Color(26, 179, 148));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_lnameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_lnameActionPerformed
    {//GEN-HEADEREND:event_txt_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lnameActionPerformed

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_fnameActionPerformed
    {//GEN-HEADEREND:event_txt_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnameActionPerformed

    private void txt_mnameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_mnameActionPerformed
    {//GEN-HEADEREND:event_txt_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mnameActionPerformed

    private void txt_contact_noActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_contact_noActionPerformed
    {//GEN-HEADEREND:event_txt_contact_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contact_noActionPerformed

    private void txt_adhar_noActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_adhar_noActionPerformed
    {//GEN-HEADEREND:event_txt_adhar_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adhar_noActionPerformed

    private void txt_account_noActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_account_noActionPerformed
    {//GEN-HEADEREND:event_txt_account_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_account_noActionPerformed

    private void textField7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textField7ActionPerformed
    {//GEN-HEADEREND:event_textField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField7ActionPerformed

    private void txt_roleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_roleActionPerformed
    {//GEN-HEADEREND:event_txt_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_roleActionPerformed

    private void txt_email_idActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_email_idActionPerformed
    {//GEN-HEADEREND:event_txt_email_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_email_idActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_submitActionPerformed
    {//GEN-HEADEREND:event_btn_submitActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","Thoke@123");
            
           String query;
           query = "INSERT INTO `medical_store`.`employee` (`fname`, `mname`, `lname`, `emp_role`, `contact_no`, `gender`, `email_id`, `adhar_no`, `dob`, `joining_date`, `salary`, `account_no`, `address`) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
           
           PreparedStatement pst = con.prepareStatement(query);

            java.util.Date utilDate = date_bdate.getDate();
            java.sql.Date dob = new java.sql.Date(utilDate.getTime());
            
            java.util.Date utilDate2 = date_jdate.getDate();
            java.sql.Date jd = new java.sql.Date(utilDate2.getTime());
            
           String atr="";
           pst.setString(1,txt_fname.getText());
           pst.setString(2,txt_mname.getText());
           pst.setString(3,txt_lname.getText());
           pst.setString(4,txt_role.getText());
           pst.setString(5,txt_contact_no.getText());
           pst.setString(6, (String) cmb_gender.getSelectedItem());
           pst.setString(7,txt_email_id.getText());
           pst.setString(8,txt_adhar_no.getText());
           pst.setDate(9, dob);
           pst.setDate(10, jd);
           pst.setString(11,txt_salary.getText());
           pst.setString(12,txt_account_no.getText());
           pst.setString(13,txt_area_address.getText());
           
           pst.executeUpdate();
           
           JOptionPane.showMessageDialog(this,"Record Inserted Successfully !!");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Record Not Inserted ! "+e);
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void txt_salaryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_salaryActionPerformed
    {//GEN-HEADEREND:event_txt_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salaryActionPerformed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_uploadActionPerformed
    {//GEN-HEADEREND:event_btn_uploadActionPerformed
        // TODO add your handling code here:
        
        emp_photo ep = new emp_photo();
        ep.setVisible(true);
    }//GEN-LAST:event_btn_uploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Employee_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Employee_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Employee_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Employee_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                Employee_form ef = new Employee_form();
                 
                ef.setLocationRelativeTo(null);
                ef.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_submit;
    private javax.swing.JButton btn_upload;
    private javax.swing.JComboBox<String> cmb_gender;
    private com.toedter.calendar.JDateChooser date_bdate;
    private com.toedter.calendar.JDateChooser date_jdate;
    private javax.swing.JScrollBar jScrollBar1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Label lbl_photo;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.TextField textField7;
    private java.awt.TextField txt_account_no;
    private java.awt.TextField txt_adhar_no;
    private java.awt.TextArea txt_area_address;
    private java.awt.TextField txt_contact_no;
    private java.awt.TextField txt_email_id;
    private java.awt.TextField txt_fname;
    private java.awt.TextField txt_lname;
    private java.awt.TextField txt_mname;
    private java.awt.TextField txt_role;
    private java.awt.TextField txt_salary;
    // End of variables declaration//GEN-END:variables
}
