/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medical_billing_system;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class home_page extends javax.swing.JFrame
{
    public home_page()
    {
        initComponents();
       
        BufferedImage img;
        
        String htmlText = "<html>"
                + "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>"
                + "<p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>"
                + "<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>"
                + "<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>"
                + "</html>";

        JLabel label = new JLabel(htmlText);
        
        try
        {
            img = ImageIO.read(new File("C:\\Users\\Chetana\\Downloads\\home_page.png"));
            
            Image dimg;
            
            dimg = img.getScaledInstance(lbl_bg.getWidth(), lbl_bg.getHeight(), Image.SCALE_SMOOTH);
            
            ImageIcon imageicon = new ImageIcon(dimg);
            
            lbl_bg.setIcon(imageicon);
        }
        catch(Exception e)
        {
            System.out.println("Caught  =  "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label6 = new java.awt.Label();
        panel1 = new java.awt.Panel();
        lbl_home = new java.awt.Label();
        lbl_order = new java.awt.Label();
        lbl_supplier = new java.awt.Label();
        lbl_employee = new java.awt.Label();
        panel3 = new java.awt.Panel();
        lbl_bg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_text = new javax.swing.JLabel();
        lbl_text1 = new javax.swing.JLabel();
        lbl_customer1 = new java.awt.Label();
        lbl_sign_up = new java.awt.Label();
        lbl_login = new java.awt.Label();
        lbl_delivery = new java.awt.Label();
        lbl_balance_sheet = new java.awt.Label();
        lbl_bill = new java.awt.Label();

        label3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(243, 243, 243));
        label3.setText("label1");

        label4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(243, 243, 243));
        label4.setText("label1");

        label6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(243, 243, 243));
        label6.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(26, 179, 148));

        lbl_home.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_home.setForeground(new java.awt.Color(243, 243, 243));
        lbl_home.setText("Home");

        lbl_order.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_order.setForeground(new java.awt.Color(243, 243, 243));
        lbl_order.setText("Orders");
        lbl_order.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lbl_orderMouseClicked(evt);
            }
        });

        lbl_supplier.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_supplier.setForeground(new java.awt.Color(243, 243, 243));
        lbl_supplier.setText("Supplier");
        lbl_supplier.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lbl_supplierMouseClicked(evt);
            }
        });

        lbl_employee.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_employee.setForeground(new java.awt.Color(243, 243, 243));
        lbl_employee.setText("Employees");
        lbl_employee.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lbl_employeeMouseClicked(evt);
            }
        });

        panel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 179, 148));
        jLabel1.setText("to");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 179, 148));
        jLabel2.setText("Dhanvantari !!");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 179, 148));
        jLabel3.setText("Welcome ");

        lbl_text.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_text.setForeground(new java.awt.Color(26, 179, 148));
        lbl_text.setText("An application to helps medical ");

        lbl_text1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_text1.setForeground(new java.awt.Color(26, 179, 148));
        lbl_text1.setText("stores to manage their databases");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_text, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbl_bg, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        lbl_customer1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_customer1.setForeground(new java.awt.Color(243, 243, 243));
        lbl_customer1.setText("Customer\n");
        lbl_customer1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lbl_customer1MouseClicked(evt);
            }
        });

        lbl_sign_up.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_sign_up.setForeground(new java.awt.Color(243, 243, 243));
        lbl_sign_up.setText("Sign Up");
        lbl_sign_up.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lbl_sign_upMouseClicked(evt);
            }
        });

        lbl_login.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_login.setForeground(new java.awt.Color(243, 243, 243));
        lbl_login.setText("Login");
        lbl_login.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lbl_loginMouseClicked(evt);
            }
        });

        lbl_delivery.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_delivery.setForeground(new java.awt.Color(243, 243, 243));
        lbl_delivery.setText("Deliveries");
        lbl_delivery.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lbl_deliveryMouseClicked(evt);
            }
        });

        lbl_balance_sheet.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_balance_sheet.setForeground(new java.awt.Color(243, 243, 243));
        lbl_balance_sheet.setText("Balance Sheet");
        lbl_balance_sheet.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lbl_balance_sheetMouseClicked(evt);
            }
        });

        lbl_bill.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_bill.setForeground(new java.awt.Color(243, 243, 243));
        lbl_bill.setText("Bill");
        lbl_bill.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lbl_billMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lbl_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_delivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lbl_bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_balance_sheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(lbl_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_customer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_customer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lbl_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_delivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_balance_sheet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_orderMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbl_orderMouseClicked
    {//GEN-HEADEREND:event_lbl_orderMouseClicked
        // TODO add your handling code here:
        
        order_page op = new order_page();
        op.setVisible(true);
    }//GEN-LAST:event_lbl_orderMouseClicked

    private void lbl_supplierMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbl_supplierMouseClicked
    {//GEN-HEADEREND:event_lbl_supplierMouseClicked
        // TODO add your handling code here:
        
        supplier_page sp = new supplier_page();
        sp.setVisible(true);
    }//GEN-LAST:event_lbl_supplierMouseClicked

    private void lbl_employeeMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbl_employeeMouseClicked
    {//GEN-HEADEREND:event_lbl_employeeMouseClicked
        // TODO add your handling code here:
        
        employee_page ep = new employee_page();
        ep.setVisible(true);
    }//GEN-LAST:event_lbl_employeeMouseClicked

    private void lbl_customer1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbl_customer1MouseClicked
    {//GEN-HEADEREND:event_lbl_customer1MouseClicked
        // TODO add your handling code here:
        
        cus_page cp = new cus_page();
        cp.setVisible(true);
    }//GEN-LAST:event_lbl_customer1MouseClicked

    private void lbl_sign_upMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbl_sign_upMouseClicked
    {//GEN-HEADEREND:event_lbl_sign_upMouseClicked
        // TODO add your handling code here:
        
        sign_up_form suf = new sign_up_form();
        suf.setVisible(true);
    }//GEN-LAST:event_lbl_sign_upMouseClicked

    private void lbl_loginMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbl_loginMouseClicked
    {//GEN-HEADEREND:event_lbl_loginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_loginMouseClicked

    private void lbl_deliveryMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbl_deliveryMouseClicked
    {//GEN-HEADEREND:event_lbl_deliveryMouseClicked
        // TODO add your handling code here:
        
        del_page dp = new del_page();
        dp.setVisible(true);
    }//GEN-LAST:event_lbl_deliveryMouseClicked

    private void lbl_balance_sheetMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbl_balance_sheetMouseClicked
    {//GEN-HEADEREND:event_lbl_balance_sheetMouseClicked
        // TODO add your handling code here:
        
        balance_sheet bs = new balance_sheet();
        bs.setVisible(true);
    }//GEN-LAST:event_lbl_balance_sheetMouseClicked

    private void lbl_billMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbl_billMouseClicked
    {//GEN-HEADEREND:event_lbl_billMouseClicked
        // TODO add your handling code here:
        
        bill_page bp = new bill_page();
        bp.setVisible(true);
    }//GEN-LAST:event_lbl_billMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                home_page hp = new home_page();
                
                // Get the screen size using Toolkit
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

                /*
                 // Set the size of the JFrame to be the size of the screen
                 hp.setSize(screenSize.width, screenSize.height);
                 
                 hp.setLayout(new BorderLayout());
                 */

                hp.setLocationRelativeTo(null);
                 hp.setLayout(new GridBagLayout());
                GridBagConstraints gbc = new GridBagConstraints();
                gbc.fill = GridBagConstraints.BOTH;
                hp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label6;
    private java.awt.Label lbl_balance_sheet;
    private javax.swing.JLabel lbl_bg;
    private java.awt.Label lbl_bill;
    private java.awt.Label lbl_customer1;
    private java.awt.Label lbl_delivery;
    private java.awt.Label lbl_employee;
    private java.awt.Label lbl_home;
    private java.awt.Label lbl_login;
    private java.awt.Label lbl_order;
    private java.awt.Label lbl_sign_up;
    private java.awt.Label lbl_supplier;
    private javax.swing.JLabel lbl_text;
    private javax.swing.JLabel lbl_text1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
