/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medical_billing_system;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class order_update_form extends javax.swing.JFrame
{
    int id;
    public order_update_form(int x)
    {
        id = x;
        initComponents();
        
        setDefaultCloseOperation(order_update_form.DISPOSE_ON_CLOSE);
        
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","Thoke@123");

            String query;
            
            query = "select * from `medical_store`.`sup_order` where order_id = ?";
            
            PreparedStatement pst  = con.prepareStatement(query);
            pst.setInt(1,id);
            
            ResultSet rs = pst.executeQuery();
         
            if(rs.next())
            {
                java.util.Date utilDate = rs.getDate("order_date");
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            
                txt_sup_id.setText(rs.getString("sup_id"));
                date_order_date.setDate(sqlDate);
                txt_quantity.setText(rs.getString("total_quantity"));
                txt_total_price.setText(rs.getString("total_price"));
                txt_order_status.setText(rs.getString("order_status"));
            }
           }
          catch(SQLException e)
          {
                  JOptionPane.showMessageDialog(this,"Error"+e);
          }
         try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","Thoke@123");
            
            String query = "select  * from `medical_store`.`order_has_medicines` where order_id = ?";
            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setInt(1,id);
      
            ResultSet rs;
            rs = pst.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData();
            
            DefaultTableModel table_model = (DefaultTableModel) tbl_medicines.getModel();
            
            int cols;
           
            cols = rsmd.getColumnCount();
            
            String[] colName;
            colName = new String[cols];
            
            for(int i=0;i<cols;i++)
            {
                colName[i]=rsmd.getColumnName(i+1);
            }
            
            table_model.setColumnIdentifiers(colName);
            
            String order_id,med_name,quantity,cost_price;
            
            while(rs.next())
            {
                order_id = rs.getString("order_id");
                med_name = rs.getString("med_name");
                quantity = rs.getString("quantity");
                cost_price = rs.getString("cost_price");
              
                String[] row =  {order_id,med_name,quantity,cost_price};
                
                table_model.addRow(row);
            }
            
            pst.close();
            con.close();
        }
        catch(SQLException e)
        {
               JOptionPane.showMessageDialog(this,"Error :"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panel9 = new java.awt.Panel();
        panel10 = new java.awt.Panel();
        label5 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        txt_sup_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        date_order_date = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txt_total_price = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_total_quantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_order_status = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_medicines = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        lbl_med_name = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        lbl_med_name1 = new javax.swing.JLabel();
        txt_cost_price = new javax.swing.JTextField();
        txt_med_name = new javax.swing.JTextField();
        lbl_med_name2 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel9.setBackground(new java.awt.Color(243, 243, 243));

        panel10.setBackground(new java.awt.Color(26, 179, 148));
        panel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        panel10.setForeground(new java.awt.Color(255, 255, 255));

        label5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Order Information");

        javax.swing.GroupLayout panel10Layout = new javax.swing.GroupLayout(panel10);
        panel10.setLayout(panel10Layout);
        panel10Layout.setHorizontalGroup(
            panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
        );
        panel10Layout.setVerticalGroup(
            panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Enter Supplier ID");

        txt_sup_id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("List of Ordered Medicines");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Enter Order Date");

        txt_total_price.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Enter Total Quantity");

        txt_total_quantity.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Enter Total Cost");

        txt_order_status.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Enter Order Status");

        tbl_medicines.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbl_medicines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Medicine Name", "Quantity", "Cost Price"
            }
        ));
        tbl_medicines.setRowHeight(25);
        jScrollPane2.setViewportView(tbl_medicines);

        btn_delete.setBackground(new java.awt.Color(26, 179, 148));
        btn_delete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(26, 179, 148));
        btn_add.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_addActionPerformed(evt);
            }
        });

        lbl_med_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_med_name.setText("Enter Cost Price");

        txt_quantity.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lbl_med_name1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_med_name1.setText("Enter Medicine Name");

        txt_cost_price.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_med_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lbl_med_name2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_med_name2.setText("Enter Quantity");

        btn_update.setBackground(new java.awt.Color(26, 179, 148));
        btn_update.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel9Layout = new javax.swing.GroupLayout(panel9);
        panel9.setLayout(panel9Layout);
        panel9Layout.setHorizontalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel9Layout.createSequentialGroup()
                        .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel9Layout.createSequentialGroup()
                                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_sup_id, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_med_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_med_name, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date_order_date, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_total_price, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_total_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_med_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_order_status, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_cost_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_med_name, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel9Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64))
                    .addGroup(panel9Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panel9Layout.setVerticalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_sup_id, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_order_date, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_order_status, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total_price, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_med_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_med_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_med_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cost_price, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_med_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_updateActionPerformed
    {//GEN-HEADEREND:event_btn_updateActionPerformed
        // TODO add your handling code here:

         try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","Thoke@123");

            String query;
           
            query = "UPDATE `medical_store`.`sup_order`  SET  sup_id = ?, order_date = ?, total_quantity=?, total_price=?, order_status = ? WHERE `order_id` = ?";

            PreparedStatement pst = con.prepareStatement(query);
           
             java.util.Date utilDate = date_order_date.getDate();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            
            pst.setString(1,txt_sup_id.getText());
            pst.setDate(2,sqlDate);
            pst.setString(3,txt_quantity.getText());
            pst.setString(4,txt_total_price.getText());
            pst.setString(5,txt_order_status.getText());
            pst.setInt(6,id);
           
            pst.executeUpdate();
            
            query = "delete from medical_store.order_has_medicines where order_id = ?";
            pst = con.prepareStatement(query);
            
            pst.setInt(1,id);
            
            pst.executeUpdate();
         
            // Prepare the SQL INSERT statement
            String sql = "INSERT INTO medical_store.order_has_medicines (order_id, med_name, quantity,cost_price) VALUES (?, ?, ?,?)";
            pst= con.prepareStatement(sql);

            // Get the TableModel from JTable
            DefaultTableModel model = (DefaultTableModel) tbl_medicines.getModel();

            // Loop through each row in the JTable
            for (int i = 0; i < model.getRowCount(); i++) 
            {
                // Set the values for each column
                pst.setInt(1, id);
                pst.setObject(2, model.getValueAt(i, 1));
                pst.setObject(3, model.getValueAt(i, 2));
                pst.setObject(4, model.getValueAt(i, 3));

                // Execute the INSERT statement
                pst.executeUpdate();
            }

            JOptionPane.showMessageDialog(this,"Record Updated Successfully !!");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Record Not Updated ! "+e);
        }
       
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_deleteActionPerformed
    {//GEN-HEADEREND:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) tbl_medicines.getModel();
        
        if(tbl_medicines.getSelectedRowCount()==1)
        {
            model.removeRow(tbl_medicines.getSelectedRow());
        }
        else
        {
            if(tbl_medicines.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"Table is Empty!!");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Please Select Single Row for Delete!!");
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_addActionPerformed
    {//GEN-HEADEREND:event_btn_addActionPerformed
        // TODO add your handling code here:
        
        if(txt_med_name.getText().equals("") || txt_total_quantity.getText().equals("") || txt_cost_price.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter All Data!!");
        }
        else
        {
            String[] data = {String.valueOf(id),txt_med_name.getText(),txt_total_quantity.getText(),txt_cost_price.getText()};
            
            DefaultTableModel model = (DefaultTableModel) tbl_medicines.getModel();
            
            model.addRow(data);
            
            JOptionPane.showMessageDialog(this, "Data Added Successfully!!");
            
            txt_med_name.setText("");
            txt_total_quantity.setText("");
            txt_cost_price.setText("");
        }
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(order_update_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(order_update_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(order_update_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(order_update_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                order_update_form frame = new order_update_form(0);
                 
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private com.toedter.calendar.JDateChooser date_order_date;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label5;
    private javax.swing.JLabel lbl_med_name;
    private javax.swing.JLabel lbl_med_name1;
    private javax.swing.JLabel lbl_med_name2;
    private java.awt.Panel panel10;
    private java.awt.Panel panel9;
    private javax.swing.JTable tbl_medicines;
    private javax.swing.JTextField txt_cost_price;
    private javax.swing.JTextField txt_med_name;
    private javax.swing.JTextField txt_order_status;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_sup_id;
    private javax.swing.JTextField txt_total_price;
    private javax.swing.JTextField txt_total_quantity;
    // End of variables declaration//GEN-END:variables
}
