/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package medical_billing_system;

import java.sql.*;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

public class update_emp_form extends javax.swing.JFrame
{
    int x;
    
    public update_emp_form(int x)
    {
        initComponents();
        this.x=x;
        
        setDefaultCloseOperation(update_emp_form.DISPOSE_ON_CLOSE);
        
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","Thoke@123");

            String query;
            
            query = "select * from `medical_store`.`employee` where emp_id = ?";
            
            PreparedStatement pst  = con.prepareStatement(query);
            pst.setInt(1,x);
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next())
            {
                txt_fname.setText(rs.getString("fname"));
                txt_mname.setText(rs.getString("mname"));
                txt_lname.setText(rs.getString("lname"));
                txt_role.setText(rs.getString("emp_role"));
                txt_contact_no.setText(rs.getString("contact_no"));
                txt_gender.setText(rs.getString("gender"));
                txt_email_id.setText(rs.getString("email_id"));
                txt_adhar_no.setText(rs.getString("adhar_no"));
                txt_dob.setText(rs.getString("dob"));
                txt_joining_date.setText(rs.getString("joining_date"));
                txt_salary.setText(rs.getString("salary"));
                txt_account_no.setText(rs.getString("account_no"));
                txt_area_address.setText(rs.getString("address"));
                 }
           }
          catch(Exception e)
          {
                  JOptionPane.showMessageDialog(this,"Error"+e);
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        label1 = new java.awt.Label();
        panel3 = new java.awt.Panel();
        label2 = new java.awt.Label();
        txt_lname = new java.awt.TextField();
        label3 = new java.awt.Label();
        txt_fname = new java.awt.TextField();
        label4 = new java.awt.Label();
        txt_mname = new java.awt.TextField();
        label5 = new java.awt.Label();
        txt_contact_no = new java.awt.TextField();
        label7 = new java.awt.Label();
        txt_adhar_no = new java.awt.TextField();
        label8 = new java.awt.Label();
        label10 = new java.awt.Label();
        txt_role = new java.awt.TextField();
        label11 = new java.awt.Label();
        txt_email_id = new java.awt.TextField();
        label9 = new java.awt.Label();
        txt_area_address = new java.awt.TextArea();
        label12 = new java.awt.Label();
        txt_joining_date = new java.awt.TextField();
        label13 = new java.awt.Label();
        txt_dob = new java.awt.TextField();
        label6 = new java.awt.Label();
        label14 = new java.awt.Label();
        txt_salary = new java.awt.TextField();
        txt_account_no = new java.awt.TextField();
        txt_gender = new java.awt.TextField();
        btn_update = new java.awt.Button();
        jScrollBar1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(243, 243, 243));

        panel2.setBackground(new java.awt.Color(26, 179, 148));
        panel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        panel2.setForeground(new java.awt.Color(255, 255, 255));

        label1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Employee Information");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel3.setBackground(new java.awt.Color(243, 243, 243));
        panel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        label2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label2.setText("Enter Middle Name ");

        txt_lname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_lname.setForeground(new java.awt.Color(102, 102, 102));
        txt_lname.setText("textField1");
        txt_lname.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_lnameActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label3.setText("Enter First Name ");

        txt_fname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_fname.setForeground(new java.awt.Color(102, 102, 102));
        txt_fname.setText("textField1");
        txt_fname.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_fnameActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label4.setText("Enter Last Name ");

        txt_mname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_mname.setForeground(new java.awt.Color(102, 102, 102));
        txt_mname.setText("textField1");
        txt_mname.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_mnameActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label5.setText("Enter DOB");

        txt_contact_no.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_contact_no.setForeground(new java.awt.Color(102, 102, 102));
        txt_contact_no.setText("textField1");
        txt_contact_no.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_contact_noActionPerformed(evt);
            }
        });

        label7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label7.setText("Enter Adhar No");

        txt_adhar_no.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_adhar_no.setForeground(new java.awt.Color(102, 102, 102));
        txt_adhar_no.setText("textField1");
        txt_adhar_no.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_adhar_noActionPerformed(evt);
            }
        });

        label8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label8.setText("Select Gender");

        label10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label10.setText("Enter Role");

        txt_role.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_role.setForeground(new java.awt.Color(102, 102, 102));
        txt_role.setText("textField1");
        txt_role.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_roleActionPerformed(evt);
            }
        });

        label11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label11.setText("Enter Email ID");

        txt_email_id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_email_id.setForeground(new java.awt.Color(102, 102, 102));
        txt_email_id.setText("textField1");
        txt_email_id.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_email_idActionPerformed(evt);
            }
        });

        label9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label9.setText("Enter Address");

        txt_area_address.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_area_address.setForeground(new java.awt.Color(102, 102, 102));

        label12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label12.setText("Enter Contact No");

        txt_joining_date.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_joining_date.setForeground(new java.awt.Color(102, 102, 102));
        txt_joining_date.setText("textField1");
        txt_joining_date.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_joining_dateActionPerformed(evt);
            }
        });

        label13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label13.setText("Enter Joining Date");

        txt_dob.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_dob.setForeground(new java.awt.Color(102, 102, 102));
        txt_dob.setText("textField1");
        txt_dob.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_dobActionPerformed(evt);
            }
        });

        label6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label6.setText("Enter Salary");

        label14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label14.setText("Enter Account No");

        txt_salary.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_salary.setForeground(new java.awt.Color(102, 102, 102));
        txt_salary.setText("textField1");
        txt_salary.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_salaryActionPerformed(evt);
            }
        });

        txt_account_no.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_account_no.setForeground(new java.awt.Color(102, 102, 102));
        txt_account_no.setText("textField1");
        txt_account_no.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_account_noActionPerformed(evt);
            }
        });

        txt_gender.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_gender.setForeground(new java.awt.Color(102, 102, 102));
        txt_gender.setText("textField1");
        txt_gender.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_genderActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(26, 179, 148));
        btn_update.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setLabel("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_role, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email_id, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_contact_no, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_account_no, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_joining_date, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_adhar_no, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panel3Layout.createSequentialGroup()
                                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(609, 609, 609)))
                            .addComponent(txt_area_address, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE))))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_contact_no, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txt_role, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txt_gender, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_email_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_adhar_no, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_joining_date, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_account_no, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_area_address, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jScrollBar1.setBackground(new java.awt.Color(26, 179, 148));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_lnameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_lnameActionPerformed
    {//GEN-HEADEREND:event_txt_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lnameActionPerformed

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_fnameActionPerformed
    {//GEN-HEADEREND:event_txt_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnameActionPerformed

    private void txt_mnameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_mnameActionPerformed
    {//GEN-HEADEREND:event_txt_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mnameActionPerformed

    private void txt_contact_noActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_contact_noActionPerformed
    {//GEN-HEADEREND:event_txt_contact_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contact_noActionPerformed

    private void txt_adhar_noActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_adhar_noActionPerformed
    {//GEN-HEADEREND:event_txt_adhar_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adhar_noActionPerformed

    private void txt_roleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_roleActionPerformed
    {//GEN-HEADEREND:event_txt_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_roleActionPerformed

    private void txt_email_idActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_email_idActionPerformed
    {//GEN-HEADEREND:event_txt_email_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_email_idActionPerformed

    private void txt_joining_dateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_joining_dateActionPerformed
    {//GEN-HEADEREND:event_txt_joining_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_joining_dateActionPerformed

    private void txt_dobActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_dobActionPerformed
    {//GEN-HEADEREND:event_txt_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dobActionPerformed

    private void txt_salaryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_salaryActionPerformed
    {//GEN-HEADEREND:event_txt_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salaryActionPerformed

    private void txt_account_noActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_account_noActionPerformed
    {//GEN-HEADEREND:event_txt_account_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_account_noActionPerformed

    private void txt_genderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txt_genderActionPerformed
    {//GEN-HEADEREND:event_txt_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_genderActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_updateActionPerformed
    {//GEN-HEADEREND:event_btn_updateActionPerformed
        // TODO add your handling code here:

        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","Thoke@123");

            String query;
           
            query = "UPDATE `medical_store`.`employee`  SET  `fname`=?, `mname`=?, `lname`=?, `emp_role`=?, `contact_no`=?, `gender`=?, `email_id`=?,`adhar_no`=?,`dob`=?, `joining_date`=?, `salary`=?, `account_no`=?, `address`=?  WHERE `emp_id` = ?";

            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setInt(14, x);

            pst.setString(1,txt_fname.getText());
            pst.setString(2,txt_mname.getText());
            pst.setString(3,txt_lname.getText());
            pst.setString(4,txt_role.getText());
            pst.setString(5,txt_contact_no.getText());
            pst.setString(6,txt_gender.getText());
            pst.setString(7,txt_email_id.getText());
            pst.setString(8,txt_adhar_no.getText());
            pst.setString(9,txt_dob.getText());
            pst.setString(10,txt_joining_date.getText());
            pst.setString(11,txt_salary.getText());
            pst.setString(12,txt_account_no.getText());
            pst.setString(13,txt_area_address.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"Record Updated Successfully !!");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Record Not Updated ! "+e);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(update_emp_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(update_emp_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(update_emp_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(update_emp_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                update_emp_form frame = new  update_emp_form(0);
                 
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_update;
    private javax.swing.JScrollBar jScrollBar1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.TextField txt_account_no;
    private java.awt.TextField txt_adhar_no;
    private java.awt.TextArea txt_area_address;
    private java.awt.TextField txt_contact_no;
    private java.awt.TextField txt_dob;
    private java.awt.TextField txt_email_id;
    private java.awt.TextField txt_fname;
    private java.awt.TextField txt_gender;
    private java.awt.TextField txt_joining_date;
    private java.awt.TextField txt_lname;
    private java.awt.TextField txt_mname;
    private java.awt.TextField txt_role;
    private java.awt.TextField txt_salary;
    // End of variables declaration//GEN-END:variables
}
